import dlt
from pyspark.sql import functions as F
from pyspark.sql.types import *

# Gold Layer: Total Sales Count (Streaming Aggregation)
# -----------------------------------------------------
# This table calculates the total number of car sales processed so far by
# performing a streaming aggregation on the carsales_silver table. Unlike
# df.count(), which returns a Python integer, this transformation uses
# Spark's aggregation functions to produce a DataFrame output, which is
# required by Delta Live Tables.
#
# Key points:
# - Uses dlt.read_stream() so the aggregation updates continuously as new
#   sales events arrive.
# - Performs a count aggregation on sale_id to compute the total number of
#   valid sales records.
# - Produces a simple, single-row Gold table that can be used directly in
#   dashboards and KPI reporting.
@dlt.table(
    name="sales_count_gold",
    comment="Counts the number of sales till now"
)
def sales_count_gold():
    df = dlt.read_stream("carsales_silver")

    sales_count_df = df.agg(
        F.count("sale_id").alias("sales_count")
    )

    return sales_count_df

# Gold Layer: Revenue by Manufacturer per Year
# --------------------------------------------
# This table computes the total revenue generated by each car manufacturer with number of units sold
# for each calendar year, using the curated Silver-level fact data.
# 
# Key points:
# - Reads from carsales_silver in streaming mode so that the KPI updates
#   automatically as new sales records arrive.
# - Extracts the year from sale_date using Spark's date functions.
# - Aggregates revenue using SUM(price), and rounds the resulting amount
#   to two decimal places and counts the number of units sold per each manufacturer for reporting consistency.
# - Produces a clean, analytical table suitable for dashboards and time-
#   based trend analysis.
@dlt.table(
    name="manufacturer_revenue_per_year_gold",
    comment="Revenue generated by each Car Manufacturer per Year"
)
def manufacturer_revenue_per_year_gold():

    df = dlt.read_stream("carsales_silver")

    # Compute yearly revenue per manufacturer with number of sold units
    manufacturer_revenue_per_year_df = (
        df.groupBy(
            "car_manufacturer",
            F.year("sale_date").alias("year")
        )
        .agg(
            F.round(F.sum("price"), 2).alias("revenue"),
            F.count("sale_id").alias("units_sold")
        )
        .orderBy(F.desc("revenue"))
    )
    return manufacturer_revenue_per_year_df

# Gold Layer: Most Sold Car Models
# --------------------------------
# This table identifies the most frequently sold car models across the entire
# dataset. It uses the curated Silver fact table and performs a streaming
# aggregation so results update automatically as new sales events arrive.
#
# Key points:
# - Reads from carsales_silver using dlt.read_stream(), enabling continuous
#   updates as streaming data arrives.
# - Groups by model_name and car_manufacturer to compute total units sold.
# - Uses COUNT(sale_id) to derive how many times each model was purchased.
# - Orders results in descending order of units_sold to reveal top-selling
#   models for dashboards and ranking analytics.
#
# The resulting table is ideal for identifying popularity trends,
# manufacturer performance, and model-level demand patterns.
@dlt.table(
    name="most_sold_models_gold",
    comment="Most Sold Models"
)
def most_sold_models_gold():
    df = dlt.read_stream("carsales_silver")
    most_sold_models_df = (
        df.groupBy(
            "model_name","car_manufacturer"
        )
        .agg(
            F.count("sale_id").alias("units_sold"))
        .orderBy(F.desc("units_sold"))
    )
    return most_sold_models_df

# Gold Layer: Dealer Performance Summary
# ---------------------------------------
# This table evaluates dealer performance based on the total number of car
# sales completed by each dealer. Streaming reads from the Silver fact layer
# ensure continuous updates as new sales arrive.
#
# Key points:
# - Joins carsales_silver (fact) with dealers_silver (dimension) to enrich
#   dealer attributes for accurate reporting.
# - Aggregates by dealer_id, dealer_name, branch_id, and manufacturer to
#   compute the total number of units sold by each dealer.
# - Ranks dealers by units_sold to highlight top performers.
# - Produces a clean, analytics-ready dataset for dashboards and KPI views.
import dlt
from pyspark.sql import functions as F

@dlt.table(
    name="dealers_performance_gold",
    comment="Performance of Dealers based on total units sold."
)
def dealers_performance_gold():

    # Fact table (streaming)
    carsales_df = dlt.read_stream("carsales_silver")

    # Dimension table (batch) - RENAME car_manufacturer to avoid ambiguity
    dealers_df = (
        dlt.read("dealers_silver")
        .select(
            F.col("dealer_id").alias("sale_dealer_id"),
            "dealer_name",
            F.col("branch_id").alias("branch_id_number"),
            F.col("car_manufacturer").alias("dealer_manufacturer")
        )
    )

    # Join + aggregation
    dealers_performance_df = (
        carsales_df.join(
            dealers_df,
            carsales_df.dealer_id == dealers_df.sale_dealer_id,
            "inner"
        )
        .groupBy(
            "sale_dealer_id",
            "dealer_name",
            "branch_id_number",
            "dealer_manufacturer"
        )
        .agg(F.count("sale_id").alias("units_sold"))
        .orderBy(F.desc("units_sold"))
        .select(
            "sale_dealer_id",
            "dealer_name",
            "units_sold",
            "branch_id_number",
            "dealer_manufacturer"
        )
    )

    return dealers_performance_df


# Gold Layer: Customers' Most Preferred Payment Methods
# -----------------------------------------------------
# This table analyzes the Silver-level fact data to determine which payment
# methods customers prefer most. Since carsales_silver is a streaming table,
# this Gold aggregation stays continuously updated as new sales records arrive.
#
# Key points:
# - Reads from carsales_silver using dlt.read_stream() to maintain real-time
#   updates in downstream dashboards.
# - Groups data by payment_mode and counts the number of sales per method.
# - Orders results in descending order of Total to reveal the most popular
#   payment options.
#
# This table supports analytical insights such as customer purchasing behavior,
# financial trends, and payment mode adoption across years and regions.
@dlt.table(
    name="customers_preferred_payment_gold",
    comment="Customers' Most Preferred Payment Methods"
)
def customers_preferred_payment_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("payment_mode")
        .agg(F.count("sale_id").alias("Total"))
        .orderBy(F.desc("Total"))
    )

# Gold Layer: Most Preferred Vehicle Types
# ----------------------------------------
# This table determines which types of vehicles (SUV, Sedan, Hatchback, etc.)
# are most frequently purchased based on Silver-level car sales data.
# Since carsales_silver is a streaming source, the aggregation updates
# continuously as new sales records arrive.
#
# Key points:
# - Uses dlt.read_stream() to ensure real-time updates in dashboards.
# - Groups sales by vehicle type and counts total units sold.
# - Orders results by Total in descending order to highlight popularity trends.
#
# This summary table is ideal for understanding market demand, customer
# preferences, and category-level performance across manufacturers.
@dlt.table(
    name="most_preferred_vehicle_type_gold",
    comment="Most Preferred Vehicle Types Based on Units Sold"
)
def most_preferred_vehicle_type_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("type")
        .agg(F.count("sale_id").alias("Total"))
        .orderBy(F.desc("Total"))
    )

# Gold Layer: Most Preferred Transmission & Fuel Type Combinations
# ----------------------------------------------------------------
# This table identifies the most popular combinations of transmission type
# (Manual, Automatic, etc.) and fuel type (Petrol, Diesel, Electric, etc.)
# based on real-time car sales trends. Since carsales_silver is a streaming
# source, results update continuously as new car sales arrive.
#
# Key points:
# - Groups records by both transmission_type and fuel_type to reveal combined
#   customer preferences rather than isolated features.
# - Uses COUNT(sale_id) to determine total units sold for each combination.
# - Orders results in descending order to highlight the most demanded drivetrain
#   and fuel-type pairings.
#
# This Gold table supports insightful analysis for product planning, inventory
# management, and understanding emerging customer trends across vehicle types.
@dlt.table(
    name="most_preferred_transmission_fuel_gold",
    comment="Most Preferred Transmission type and Fuel Type Based on Units Sold"
)
def most_preferred_transmission_fuel_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("transmission_type", "fuel_type")
        .agg(F.count("sale_id").alias("Total_Units"))
        .orderBy(F.desc("Total_Units"))
    )

# Gold Layer: Car Sales Revenue by Country and Region
# ----------------------------------------------------
# This table calculates the total revenue generated from car sales across
# different countries and regions. Reading from the streaming Silver fact
# table ensures that revenue totals update automatically as new sales occur.
#
# Key points:
# - Groups records by country and region to provide a geographical revenue view.
# - Uses SUM(price) to compute aggregate revenue per location.
# - Orders results in descending order of Total_Revenue to highlight the
#   highest-performing regions.
#
# This Gold table enables powerful geographical insights for dashboards,
# performance analysis, expansion strategies, and regional business planning.
@dlt.table(
    name="car_sales_revenue_by_country_region_gold",
    comment="Car Sales Revenue aggregated by Country and Region."
)
def car_sales_revenue_by_country_region_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("country", "region")
        .agg(F.sum("price").alias("Total_Revenue"))
        .orderBy(F.desc("Total_Revenue"))
    )

# Gold Layer: Most Preferred Car Model & Manufacturer by Country and Region
# -------------------------------------------------------------------------
# This table determines the most popular car models and manufacturers in each
# country and region using streaming aggregation over the Silver fact data.
#
# Key points:
# - Uses dlt.read_stream() for real-time updates as new car sales arrive.
# - Groups by model, manufacturer, country, and region to expose detailed
#   geographical and brand-level popularity.
# - Counts total vehicles sold and orders results from highest to lowest.
#
# This Gold table is ideal for understanding region-wise demand, market share,
# and vehicle preferences across both models and manufacturers.
@dlt.table(
    name="most_preferred_car_model_manufacturer_gold",
    comment="Most Preferred Car Model and Manufacturer by Country and Region"
)
def most_preferred_car_model_manufacturer_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("model_name", "car_manufacturer", "country", "region")
        .agg(F.count("sale_id").alias("Total_Units"))
        .orderBy(F.desc("Total_Units"))
    )

# Gold Layer: Total Revenue from All Cars Sold
# --------------------------------------------
# This table computes the cumulative revenue generated from all car sales
# processed in the pipeline. Since carsales_silver is a streaming table,
# this aggregation updates continuously as new sales events are ingested.
#
# Key points:
# - Uses dlt.read_stream() to maintain real-time revenue tracking.
# - Aggregates the `price` column using SUM to compute total revenue.
# - Returns a single-row Gold table ideal for dashboards, KPIs, and financial
#   summaries.
#
# This Gold metric provides an important high-level financial insight into the
# overall performance of car sales across all years and dimensions.
@dlt.table(
    name="total_revenue_gold",
    comment="Total Revenue of All Cars Sold"
)
def total_revenue_gold():
    return (
        dlt.read_stream("carsales_silver")
        .agg(F.sum("price").alias("Total_Revenue"))
    )

# Gold Layer: Most Luxurious Car Models
# -------------------------------------
# This table identifies the costliest (highest-priced) car models sold across
# all years, using the curated Silver fact table. Since carsales_silver is a
# streaming source, results update in real-time as more high-value cars are
# sold.
#
# Key points:
# - Aggregates by model_name and car_manufacturer to compute the maximum
#   recorded sale price for each model.
# - Sorts results in descending order to highlight the top luxury models.
# - Ideal for premium market analysis, luxury segment insights, and pricing
#   trend dashboards.
@dlt.table(
    name="car_models_by_luxury_gold",
    comment="Most Costliest (Luxury) Car Models Based on Maximum Sale Price"
)
def car_models_by_luxury_gold():
    return (
        dlt.read_stream("carsales_silver")
        .groupBy("model_name", "car_manufacturer")
        .agg(F.max("price").alias("max_price"))
        .orderBy(F.desc("max_price"))
    )