# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %fs ls "/Volumes/dab_car_sales_dev/default/carsales"

# COMMAND ----------

from pyspark.sql.types import (
    StructType, StructField,
    StringType, IntegerType, DoubleType, TimestampType
)

car_sales_schema = StructType([
    StructField("sale_id", StringType(), True),
    StructField("sale_date", TimestampType(), True),
    StructField("car_manufacturer", StringType(), True),
    StructField("model_name", StringType(), True),
    StructField("type", StringType(), True),
    StructField("fuel_type", StringType(), True),
    StructField("transmission_type", StringType(), True),
    StructField("vin", StringType(), True),
    StructField("price", DoubleType(), True),
    StructField("customer_id", IntegerType(), True),
    StructField("customer_name", StringType(), True),
    StructField("payment_mode", StringType(), True),
    StructField("branch_id", IntegerType(), True),
    StructField("country", StringType(), True),
    StructField("region", StringType(), True),
    StructField("dealer_id", IntegerType(), True)
])


# COMMAND ----------

carsales_df=spark.read.format("csv").option("header","true").schema(car_sales_schema).load("/Volumes/dab_car_sales_dev/default/carsales/carsales_yearwise/carsalesdata_2015.csv")

# COMMAND ----------

display(carsales_df)

# COMMAND ----------

carsales_df.printSchema()

# COMMAND ----------

branches_df=spark.read.format("csv").option("header","true").option("inferSchema","true").load("/Volumes/dab_car_sales_dev/default/carsales/branches/")
display(branches_df.limit(50))

# COMMAND ----------

branches_df.printSchema()

# COMMAND ----------

customers_df=spark.read.format("csv").option("header","true").option("inferSchema","true").load("/Volumes/dab_car_sales_dev/default/carsales/customers/")
display(customers_df.limit(50))

# COMMAND ----------

customers_df.printSchema()

# COMMAND ----------

dealers_df=spark.read.format("csv").option("header","true").option("inferSchema","true").load("/Volumes/dab_car_sales_dev/default/carsales/dealers/")
display(dealers_df.limit(50))

# COMMAND ----------

dealers_df.printSchema()

# COMMAND ----------

